Repository Xyaneon/Xyaneon.Games.Cards, pull requests merged in 2023-01, with the labels that each got.

#63 feat: shift to shuffle algorithm as delegate
  Xyaneon.Games.Cards.Test/DrawPileTests.cs
  Xyaneon.Games.Cards.Test/Extensions/AssertExtensions.cs
  Xyaneon.Games.Cards.Test/Helpers/IntCard.cs
  Xyaneon.Games.Cards/DefaultShuffleAlgorithm.cs
  Xyaneon.Games.Cards/DrawPile.cs
  Xyaneon.Games.Cards/IDrawPile.cs
  Xyaneon.Games.Cards/IShuffleAlgorithm.cs
Labels: enhancement

#64 ci(test): add code coverage
  .github/workflows/dotnet.yml
  README.md
  Xyaneon.Games.Cards.Test/Xyaneon.Games.Cards.Test.csproj
  Xyaneon.Games.Cards.Test/coverlet.runsettings
Labels: enhancement, testing, continuous-integration

#66 test: add unit tests for DefaultShuffleAlgorithm
  Xyaneon.Games.Cards.Test/DefaultShuffleAlgorithmTests.cs
Labels: testing

#70 Removed repeating comments from unit testing code
  Xyaneon.Games.Cards.Test/DrawPileTests.cs
Labels: testing

#69 test: improve test coverage of DrawPile
  Xyaneon.Games.Cards.Test/DrawPileTests.cs
Labels: testing

#71 test: add more StandardPlayingCardDeck tests
  Xyaneon.Games.Cards.Test/StandardPlayingCardDeckTests.cs
Labels: testing

#72 style: add .editorconfig file
  .editorconfig
Labels: enhancement

#73 test: improve StandardPlayingCard unit test coverage
  Xyaneon.Games.Cards.Test/StandardPlayingCardTests.cs
Labels: testing

#74 feat!: replace IShuffleAlgorithm with ShuffleFunction
  README.md
  Xyaneon.Games.Cards.Test/DefaultShuffleAlgorithmTests.cs
  Xyaneon.Games.Cards/DefaultShuffleAlgorithm.cs
  Xyaneon.Games.Cards/DrawPile.cs
  Xyaneon.Games.Cards/IDrawPile.cs
  Xyaneon.Games.Cards/IShuffleAlgorithm.cs
  Xyaneon.Games.Cards/ShuffleFunction.cs
Labels: enhancement
